#
# Makefile for tee post launch components
#

obj-$(CONFIG_TEE_POST_LAUNCH) += tee_post_launch.o
tee_post_launch-objs += post_launch.o
tee_post_launch-objs += libelfloader/elf32_ld.o
tee_post_launch-objs += libelfloader/elf64_ld.o
tee_post_launch-objs += libelfloader/elf_ld.o
